name: Terraform Plan Actions
run-name: ${{ github.actor }} is running Terraform Plan
on: 
  pull_request:
    branches: 
      - main
jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      
      - name: gcloud-auth
        uses: 'google-github-actions/auth@v2'
        with: 
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: terraform-setup
        uses: hashicorp/setup-terraform@v3

      - name: terraform-init
        run: terraform init -input=false

      - name: terraform-plan
        run: terraform plan -input=false
